var _ = require('lodash');

module.exports = {
    "/territory": {
        'method': 'post',
        'params': {
            territoryName: 111,
            parentTerritoryId: 11
        },
        response: "1"
    },

    '/territory/:id/base-info': {
        response: {
            "id": 6,
            "bizId": 101,
            "territoryName": "交易平台-普通客户123",
            "parentTerritoryId": 2
        }
    },

    '/territory/:id': {
        method: 'delete',
        response: "11"
    },

    '/territory/base-info':{
        response:{
            parentTerritoryId: 1,
            territoryName: "adda",
            chiefLeaderId: 1,
            territoryChiefName:"adadad",
            notOnlineMutGroupCountLimit: 12,
            notOnlineSingleGroupCountLimit: 33
        }
    },

    '/territory/queryTerritoryBreadCrumbs':{
        response: [
            {
                "id": 6,
                "bizId": 101,
                "territoryName": "交易平台",
                "parentTerritoryId": 2
            },
            {
                "id": 7,
                "bizId": 101,
                "territoryName": "交易平台-普通客户123",
                "parentTerritoryId": 2
            },
            {
                "id": 8,
                "bizId": 101,
                "territoryName": "常州",
                "parentTerritoryId": 2
            }
        ]
    },

    '/common/enums': {
        response: {
            "province": [{
                "text": "北京",
                "value": 1
            }, {
                "text": "天津",
                "value": 2
            }, {
                "text": "河北",
                "value": 3
            }, {
                "text": "山西",
                "value": 4
            }, {
                "text": "内蒙古",
                "value": 5
            }, {
                "text": "辽宁",
                "value": 6
            }, {
                "text": "吉林",
                "value": 7
            }, {
                "text": "黑龙江",
                "value": 8
            }, {
                "text": "上海",
                "value": 9
            }, {
                "text": "江苏",
                "value": 10
            }, {
                "text": "浙江",
                "value": 11
            }, {
                "text": "安徽",
                "value": 12
            }, {
                "text": "福建",
                "value": 13
            }, {
                "text": "江西",
                "value": 14
            }, {
                "text": "山东",
                "value": 15
            }, {
                "text": "河南",
                "value": 16
            }, {
                "text": "湖北",
                "value": 17
            }, {
                "text": "湖南",
                "value": 18
            }, {
                "text": "广东",
                "value": 19
            }, {
                "text": "广西",
                "value": 20
            }, {
                "text": "海南",
                "value": 21
            }, {
                "text": "重庆",
                "value": 22
            }, {
                "text": "四川",
                "value": 23
            }, {
                "text": "贵州",
                "value": 24
            }, {
                "text": "云南",
                "value": 25
            }, {
                "text": "西藏",
                "value": 26
            }, {
                "text": "陕西",
                "value": 27
            }, {
                "text": "甘肃",
                "value": 28
            }, {
                "text": "青海",
                "value": 29
            }, {
                "text": "宁夏",
                "value": 30
            }, {
                "text": "新疆",
                "value": 31
            }, {
                "text": "香港",
                "value": 32
            }, {
                "text": "澳门",
                "value": 33
            }, {
                "text": "台湾",
                "value": 34
            }, {
                "text": "国外",
                "value": 100
            }, {
                "text": "新加坡",
                "value": 101
            }, {
                "text": "马来西亚",
                "value": 102
            }, {
                "text": "泰国",
                "value": 103
            }, {
                "text": "韩国",
                "value": 104
            }, {
                "text": "日本",
                "value": 105
            }, {
                "text": "柬埔寨",
                "value": 106
            }, {
                "text": "越南",
                "value": 107
            }, {
                "text": "澳大利亚",
                "value": 108
            }, {
                "text": "新西兰",
                "value": 109
            }, {
                "text": "马尔代夫",
                "value": 110
            }, {
                "text": "印度尼西亚",
                "value": 111
            }, {
                "text": "北马里亚纳群岛",
                "value": 112
            }, {
                "text": "菲律宾",
                "value": 113
            }, {
                "text": "斐济",
                "value": 114
            }, {
                "text": "毛里求斯",
                "value": 115
            }, {
                "text": "斯里兰卡",
                "value": 116
            }, {
                "text": "法国",
                "value": 117
            }, {
                "text": "美国",
                "value": 118
            }, {
                "text": "尼泊尔",
                "value": 119
            }, {
                "text": "塞舌尔",
                "value": 120
            }, {
                "text": "法属玻利尼西亚",
                "value": 121
            }, {
                "text": "印度",
                "value": 122
            }, {
                "text": "加拿大",
                "value": 123
            }, {
                "text": "奥地利",
                "value": 124
            }, {
                "text": "比利时",
                "value": 125
            }, {
                "text": "德国",
                "value": 126
            }, {
                "text": "荷兰",
                "value": 127
            }, {
                "text": "捷克",
                "value": 128
            }, {
                "text": "葡萄牙",
                "value": 129
            }, {
                "text": "瑞典",
                "value": 130
            }, {
                "text": "瑞士",
                "value": 131
            }, {
                "text": "土耳其",
                "value": 132
            }, {
                "text": "西班牙",
                "value": 133
            }, {
                "text": "希腊",
                "value": 134
            }, {
                "text": "匈牙利",
                "value": 135
            }, {
                "text": "意大利",
                "value": 136
            }, {
                "text": "英国",
                "value": 137
            }, {
                "text": "爱尔兰",
                "value": 138
            }, {
                "text": "埃及",
                "value": 139
            }, {
                "text": "摩洛哥",
                "value": 140
            }, {
                "text": "南非",
                "value": 141
            }, {
                "text": "墨西哥",
                "value": 142
            }, {
                "text": "巴西",
                "value": 143
            }, {
                "text": "阿根廷",
                "value": 144
            }, {
                "text": "智利",
                "value": 145
            }, {
                "text": "秘鲁",
                "value": 146
            }, {
                "text": "老挝",
                "value": 147
            }, {
                "text": "黎巴嫩",
                "value": 148
            }, {
                "text": "文莱",
                "value": 149
            }, {
                "text": "缅甸",
                "value": 150
            }, {
                "text": "以色列",
                "value": 151
            }, {
                "text": "约旦",
                "value": 152
            }, {
                "text": "埃塞尔比亚",
                "value": 153
            }, {
                "text": "肯尼亚",
                "value": 154
            }, {
                "text": "马达加斯加",
                "value": 155
            }, {
                "text": "坦桑尼亚",
                "value": 156
            }, {
                "text": "哥斯达黎加",
                "value": 157
            }, {
                "text": "牙买加",
                "value": 158
            }, {
                "text": "帕劳",
                "value": 159
            }],
            "biz": [{
                "text": "交易平台销售业务",
                "value": 101
            }, {
                "text": "全国电影业务",
                "value": 102
            }, {
                "text": "旅游酒店业务",
                "value": 103
            }, {
                "text": "推广业务",
                "value": 104
            }, {
                "text": "结婚业务",
                "value": 105
            }, {
                "text": "预订业务",
                "value": 106
            }]
        }
    },

    "/territory/tree": {
        "method": "get",
        "params": {
            "id": 1
        },
        "response": {
            "id": 1,
            "bizId": 105,
            "territoryName": "点评",
            "parentTerritoryId": null,
            "childrenList": [{
                "id": 2,
                "bizId": 101,
                "territoryName": "交易平台",
                "parentTerritoryId": 1,
                "childrenList": [{
                    "id": 6,
                    "bizId": 101,
                    "territoryName": "交易平台-普通客户",
                    "parentTerritoryId": 2,
                    "childrenList": [{
                        "id": 8,
                        "bizId": 101,
                        "territoryName": "普通客户-上海",
                        "parentTerritoryId": 6,
                        "childrenList": [{
                            "id": 10,
                            "bizId": 101,
                            "territoryName": "宝山",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 11,
                            "bizId": 101,
                            "territoryName": "崇明",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 12,
                            "bizId": 101,
                            "territoryName": "环上海郊区一",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 13,
                            "bizId": 101,
                            "territoryName": "环上海郊区二",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 14,
                            "bizId": 101,
                            "territoryName": "普陀/闸北",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 15,
                            "bizId": 101,
                            "territoryName": "浦东新区",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 16,
                            "bizId": 101,
                            "territoryName": "市中心",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 17,
                            "bizId": 101,
                            "territoryName": "徐闵区",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }, {
                            "id": 18,
                            "bizId": 101,
                            "territoryName": "杨浦/虹口",
                            "parentTerritoryId": 8,
                            "childrenList": null
                        }]
                    }, {
                        "id": 9,
                        "bizId": 101,
                        "territoryName": "普通客户-南京",
                        "parentTerritoryId": 6,
                        "childrenList": null
                    }]
                }]
            }, {
                "id": 3,
                "bizId": 105,
                "territoryName": "结婚",
                "parentTerritoryId": 1,
                "childrenList": null
            }, {
                "id": 4,
                "bizId": 104,
                "territoryName": "推广",
                "parentTerritoryId": 1,
                "childrenList": [{
                    "id": 7,
                    "bizId": 104,
                    "territoryName": "推广-普通客户",
                    "parentTerritoryId": 4,
                    "childrenList": null
                }, {
                    "id": 19,
                    "bizId": 104,
                    "territoryName": "推广餐饮客户",
                    "parentTerritoryId": 4,
                    "childrenList": [{
                        "id": 20,
                        "bizId": 104,
                        "territoryName": "上海推广餐饮",
                        "parentTerritoryId": 19,
                        "childrenList": [{
                            "id": 21,
                            "bizId": 104,
                            "territoryName": "上海推广餐饮-1",
                            "parentTerritoryId": 20,
                            "childrenList": [{
                                "id": 22,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-1-1",
                                "parentTerritoryId": 21,
                                "childrenList": null
                            }, {
                                "id": 23,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-1-2",
                                "parentTerritoryId": 21,
                                "childrenList": null
                            }, {
                                "id": 24,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-1-3",
                                "parentTerritoryId": 21,
                                "childrenList": null
                            }]
                        }, {
                            "id": 25,
                            "bizId": 104,
                            "territoryName": "上海推广餐饮-2",
                            "parentTerritoryId": 20,
                            "childrenList": [{
                                "id": 26,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-2-1",
                                "parentTerritoryId": 25,
                                "childrenList": null
                            }, {
                                "id": 27,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-2-2",
                                "parentTerritoryId": 25,
                                "childrenList": null
                            }, {
                                "id": 28,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-2-3",
                                "parentTerritoryId": 25,
                                "childrenList": null
                            }, {
                                "id": 29,
                                "bizId": 104,
                                "territoryName": "上海推广餐饮-2-4",
                                "parentTerritoryId": 25,
                                "childrenList": null
                            }]
                        }, {
                            "id": 30,
                            "bizId": 104,
                            "territoryName": "上海推广餐饮-3",
                            "parentTerritoryId": 20,
                            "childrenList": null
                        }, {
                            "id": 33,
                            "bizId": 0,
                            "territoryName": "上海推广餐饮-5",
                            "parentTerritoryId": 20,
                            "childrenList": [{
                                "id": 34,
                                "bizId": 0,
                                "territoryName": "上海推广餐饮-5-1",
                                "parentTerritoryId": 33,
                                "childrenList": null
                            }]
                        }]
                    }]
                }]
            }, {
                "id": 5,
                "bizId": 106,
                "territoryName": "预订",
                "parentTerritoryId": 1,
                "childrenList": null
            }]
        }
    }
}